### ISSUE TITLE
query GRIIS Belgium and citizen science database and calculate timelag

### ISSUE THREAD

**Issue by timadriaens** [alien-csi/citizen-science-timelag-study#1]
@damianooldoni we would like to compare first observation dates of species from GRIIS Belgium with first observation date from the citizen science databases on [animals](https://www.gbif.org/dataset/9a0b66df-7535-4f28-9f4e-5bc11b8b096c) and [plants](https://www.gbif.org/dataset/7f5e4129-0717-428e-876a-464fbd5d9a47/metrics). Is there a way to quickly harvest that from GBIF? The idea is we subtract both to calculate the timelag = ['first citizen science record'] - ['official first record' (= from GRIIS)]. When that date is the same, the timelag would be zero. So for instance, first record on GRIIS for taxon x is 2013, first record in CS database 2022, timelag = (2022 - 2013) = 8.

**Comment by timadriaens** [comment]
the data are analysed here https://github.com/ChrisBotella/CS_alien_detection_time_lag

**Comment by timadriaens** [comment]
So, a bit more information to perform this query, here is what we need

| GRIIS Belgium | https://doi.org/10.15468/k2aiak | https://doi.org/10.15468/smdvdo | 
| ------------- |-------------| -------------| 
| id | id  | id |
| scientificName | scientificName | scientificName | 
| eventDate | Event date | Event date |

**Comment by timadriaens** [comment]
I would then like to compare the result with what is in [this file](https://github.com/ChrisBotella/CS_alien_detection_time_lag/blob/main/timeLags_22_03_04_all_variables_clean.csv) for Belgium

**Comment by damianooldoni** [comment]
@timadriaens,  I think you can close this issue now?
